# Generic GPU Config (Other / Unknown devices)
# Used by tx11start automatically as fallback

export GALLIUM_DRIVER=virpipe
export MESA_NO_ERROR=1
export MESA_GL_VERSION_OVERRIDE=4.0
export MESA_GLES_VERSION_OVERRIDE=3.2
export mesa_glthread=true
# VirGL server: virgl_test_server_android
