# Mali GPU Config (Exynos / MediaTek / Dimensity / Helio devices)
# Used by tx11start automatically

export GALLIUM_DRIVER=virpipe
export MESA_NO_ERROR=1
export MESA_GL_VERSION_OVERRIDE=4.3COMPAT
export MESA_GLES_VERSION_OVERRIDE=3.2
export MESA_VK_WSI_PRESENT_MODE=mailbox
export MESA_VK_WSI_DEBUG=blit
export LIBGL_DRI3_DISABLE=1
export mesa_glthread=true
export vblank_mode=0
# VirGL server: virgl_test_server_android --angle-gl
