# Adreno GPU Config (Snapdragon devices)
# Used by tx11start automatically

export GALLIUM_DRIVER=virpipe
export MESA_NO_ERROR=1
export MESA_GL_VERSION_OVERRIDE=4.3COMPAT
export MESA_GLES_VERSION_OVERRIDE=3.2
export MESA_GLSL_VERSION_OVERRIDE=430
export MESA_EXTENSION_OVERRIDE=+GL_EXT_shader_texture_lod
export LIBGL_DRI3_DISABLE=1
export mesa_glthread=true
export vblank_mode=0
# VirGL server: virgl_test_server_android --angle-gl
